// Generated by https://quicktype.io

import { Image } from "../../products/interfaces/images.interface";

export interface User {


  id: number;
  idRole: number;
  mail: string;
  password?: string;
  name: string;
  lastName: string;
  idCard: string;
  state: number;
  role?: Role;
  avatar?: Image;
}

export interface Role {
  id: number;
  name: string;
}
