// Generated by https://quicktype.io

export interface User {
  id:       number;
  idRole:   number;
  mail:     string;
  password?: string;
  name:     string;
  lastName: string;
  idCard:   string;
  state:    number;
  role?:     Role;
}

export interface Role {
  id:   number;
  name: string;
}
