// Generated by https://quicktype.io

import { Client } from "../../clients/interfaces/clients.interface";
import { Product } from "../../products/interfaces/products.interfaces";

export interface Sale {
  id: number;
  idClient: number;
  date: Date;
  total: number;
  state: number;
  concepts?: Concept[];
  client?: Client;
}


export interface Concept {
  id?: number;
  idSale?: number;
  quantity: number;
  unitaryPrice: number;
  import: number;
  idProduct: number;
  state?: number;
  product?: Product;
}


